### ISSUE TITLE
не выключается димер

### ISSUE THREAD

**Issue by marsic-84** [serhiy23412/AC_dimmer-dmr-0.2.1#1]
В режиме Dimm_value, если изменять значения яркости сразу с 255 до 0 - диммер не выключает нагрузку.
Нормально работает начиная с 244, ...все что выше 245-255 - работает не корректно(((

**Comment by serhiy23412** [comment]
спасибо за комент
на выходных обязатяльно проверю и исправлю

сейчас, если вам нужно работать порогово (от 255 и резко до 0) рекомендую использовать режим ssr_switch()

**Comment by lues1980** [comment]
добавлю - такое впечатление что диммер "залипает" на высоких значениях (>240), после какого то более менее продолжительного времени работы. 
Если кратковременно поднять мощность до предела и понизить - отработает нормально. Если пару минут пробудет на максимуме - так и останется до снятия питания с микроконтроллера.

**Comment by serhiy23412** [comment]
Привет, хорошие новости
Баг с "залипанием" Dimm_value при значениях выше 245 исправлен
Новая версия залита, проверяйте
Спасибо за репорты

**Comment by andriiyll** [comment]
Проверил. Новая либа работает

**Comment by serhiy23412** [comment]
Спасибо за отзыв
