### ISSUE TITLE
Вопрос по функции Heater

### ISSUE THREAD

**Issue by DVU45** [serhiy23412/AC_dimmer-dmr-0.2.1#3]
Можно ли изменить (увеличить) диапазон значений мощности в функции Heater ?
Насколько я понимаю, за это отвечает строка
 #define MAX_HEAT_DIV 10 
в файле AC_Dimmer.cpp ?
Но это значение не должно быть больше 50?
Развейте пожалуйста мои сомнения .

**Comment by serhiy23412** [comment]
Да с момощью даного дэфайна можно увеличить диапазон. ограничений нет. но стоит помнить что чем больше величина, тем меньше частота диммрования f = 50 / с. где с - величина даной константы

**Comment by DVU45** [comment]
OK. Спасибо. Вопрос закрыт.
